name: Deploy FullStackApp
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - run: docker build -t yoyoar/react-test-app -f ./frontend/Dockerfile.dev ./frontend
            - run: docker run -e CI=true yoyoar/react-test-app npm test

            - run: docker build -t yoyoar/docker-frontend ./frontend
            - run: docker build -t yoyoar/docker-nginx ./nginx
            - run: docker build -t yoyoar/docker-backend ./backend

            - run: docker push yoyoar/docker-frontend
            - run: docker push yoyoar/docker-nginx
            - run: docker push yoyoar/docker-backend

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: fullstack-app
                  environment_name: Fullstack-docker-app-env
                  existing_bucket_name: elasticbeanstalk-ap-northeast-2-058264323492
                  region: ap-northeast-2
                  version_label: ${{ github.sha }}
                  deployment_package: deploy.zip
